"use strict";

/**
 * @ngdoc function
 * @name titanClienteV2App.decorator:TextTranslate
 * @description
 * # TextTranslate
 * Decorator of the titanClienteV2App
 */
var text_es = {
    TITULO: "SISTEMA DE GESTIÓN DE NÓMINA",
    MENSAJE_INICIAL: "Oficina Asesora de Sistemas",
    VOLVER: "Volver",
    SALIR: "Salir",
    REGISTRAR: "Registrar",
    CANCELAR: "Cancelar",
    GENERAR: "Generar",
    GENERANDO: "Generando...",
    DETALLE: "Detalle",
    GENERAR_PDF: "Generar PDF",
    SI: "Sí",
    NO: "No",
    ACTIVO: "Activo",
    INACTIVO: "Inactivo",
    SELECCIONE: "Seleccione...",
    CONFIRMAR: "Confirmar",
    BTN:{
      EDITAR:"Editar",
      BORRAR:"Eliminar",
      INACTIVAR: "Inactivar",
      ACTIVAR: "Activar"
    },
    ENERO:"Enero",
    FEBRERO:"Febrero",
    MARZO:"Marzo",
    ABRIL:"Abril",
    MAYO:"Mayo",
    JUNIO:"Junio",
    JULIO:"Julio",
    AGOSTO:"Agosto",
    SEPTIEMBRE:"Septiembre",
    OCTUBRE:"Octubre",
    NOVIEMBRE:"Noviembre",
    DICIEMBRE:"Diciembre",

    //Formulario registro nómina
    ANADIR_NOMINA: "Añadir nómina",
    TITULO_REG_NOMINA: "Registro de nómina",
    NOMBRE_NOMINA: "Nombre de la nómina",
    DESC_NOMINA: "Descripción",
    ESTADO_NOMINA: "Estado",
    OPCIONES_NOMINA: "Opciones",
    PRELIQUIDACION: "Preliquidaciones",
    TIPO_NOMINA: "Tipo de nómina",
    TITULO_NOMINA_REGIS: "Nóminas registradas",
    NOMINA_REG_CORRECTA: "Nómina registrada correctamente",
    NOMINA_REG_INCORRECTA: "Error al registrar la nómina",
    //Formulario registro preliquidacion
    ANADIR_PRELIQ: "Añadir preliquidación",
    TITULO_REG_PRELIQ: "Registro de preliquidación",
    DESC_PRELIQ: "Descripción",
    ANO_PRELIQ: "Año",
    MES_PRELIQ: "Mes",
    ESTADO_PRELIQ: "Estado",
    TITULO_PRELIQ_REGIS: "Preliquidaciones para la nómina",
    FECHA_PRELIQ: "Fecha registro",
    OPCIONES_PRELIQ: "Opciones",
    PRELIQ_REG_CORRECTA: "Preliquidación registrada correctamente",
    PRELIQ_REG_INCORRECTA: "Error al registrar la preliquidación",
    ALERTA_PRELIQUIDACION_CERRADA: "Esta preliquidación está cerrada",
    ALERTA_PRELIQUIDACION_OP: "Esta preliquidación está esperando por orden de pago",
    CAMBIO_ESTADO_OP_CORRECTO: "Se ha solicitado orden de pago",
    CAMBIOS_ESTADO_OP_INCORRECTO: "Error al solicitar orden de pago",
    CERRADA:"Cerrrada",
    ABIERTA:"Abierta",
    NEC_SOLICITADA: "Necesidad solicitada",
    OP_SOLICITADA: "Orden de pago solicitada",
    NO_PRELIQ: "No se ha generado preliquidación",
    //Interfaz de listado de personas a preliquidar
    PRELIQ_NOMINA: "Personas a preliquidar en nómina: ",
    NUM_CONTRATO: "Número de contrato",
    NOMBRE_PERSONA: "Nombre",
    DOCUMENTO: "Documento",
    VIGENCIA: "Vigencia",
    ALERTA_PERSONAS_SIN_SS: "No es posible realizar la liquidación. Las personas resaltadas no cuentan con sus datos de seguridad social completos",
    PAGOS_REALIZAR: "Personas a liquidar en el presente periodo",
    PENDIENTES_PAGO: "Personas pendientes de pago periodos anteriores",
    //Interfaz de detalle de preliquidacion
    TITULO_DETALLE_PRELIQ: "Detalle de preliquidación de la nómina",
    RESUMEN_PRELIQ: "Resumen de la preliquidación",
    CONCEPTO: "Concepto",
    VALOR: "Valor",
    NATURALEZA: "Naturaleza",
    TIPO: "Tipo",
    TOTAL: "Total",
    TOTAL_DEV: "Total devengado:",
    TOTAL_DESC: "Total descuentos:",
    TOTAL_PAGAR: "Total a pagar:",
    SUELDOS_NETOS: "Sueldos netos:",
    GENERAR_NECESIDAD: "Generar necesidad",
    GENERAR_OP: "Generar orden de pago",
    DETALLE_EMP: "Detalle del empleado",
    ALERTA_PERSONAS_SELECCIONADAS: "Debe seleccionar personas para ser liquidadas",
    ALERTA_NO_LIQUIDACION: "Esta preliquidación ya ha sido liquidada",
    TOTAL_CONT_LIQUIDADOS: "Total de contratos preliquidados",
    REALIZA_PAGO: "¿Se realizará pago?",
    //REGISTRO Y CONSULTA DE NOVEDADES
    TITULO_NOVEDADES: "Registro de novedades",
    SELECCION_PERSONA: "Selección de persona",
    AGREGAR_NOVEDAD: "Agregar novedad",
    DETALLE_NOVEDAD: "Detalle de novedades",
    ALERTA_NO_NOVEDADES: "No hay novedades registradas",
    TITULO_REG_NOVEDAD: "Registro de nueva novedad",
    NOMBRE_CONCEPTO_NOVEDAD: "Concepto",
    VALOR_CONCEPTO_NOVEDAD: "Valor Novedad",
    NUMCUOTAS_CONCEPTO_NOVEDAD: "No de cuotas",
    VALOR_CONCEPTO: "Valor",
    CUOTAS_NOV: "Cuotas",
    TIPO_CONCEPTO: "Tipo",
    FECHA_INICIO: "Fecha de inicio",
    FECHA_FIN: "Fecha de finalización",
    TITULO_EDICION_NOVEDAD: "Edición de novedad",
    FECHA_REGISTRO: "Fecha de registro",
    NOVEDAD_REG_CORRECTO: "Novedad registrada correctamente",
    NOVEDAD_REG_ERROR: "Error al registrar novedad",
    CONFIRMACION_INACTIVIDAD_NOV: "¿Está seguro que desea inactivar la novedad : ",
    INACTIVIDAD_CORRECTA_NOV: "Novedad inactivada",
    INACTIVIDAD_INCORRECTA_NOV: "Error al inactivar novedad",
    CONFIRMACION_EDICION_NOV: "¿Está seguro que desea editar la novedad : ",
    EDICION_CORRECTA_NOV: "Novedad modificada correctamente",
    EDICION_INCORRECTA_NOV: "Error al modificar novedad",
    //FORMULARIO beneficiarios
    TITULO_REG_BEN: "Registro de beneficiarios",
    TIPO_DOC_BEN: "Tipo de documento",
    NUM_DOC_BEN: "Número de documento",
    NOM_BEN: "Nombres de los beneficiarios",
    APE_BEN: "Apellido de los beneficiarios",
    PARENTESCO: "Parentesto",
    PARENTESCO_CON: "Pariente directo de",
    GENERO: "Género",
    CORREO_ELEC: "Correo electrónico",
    NUMERO_CONTACTO: "Número de contacto",
    FECHA_NAC_BEN: "Fecha de nacimiento",
    APLICA_SUB_FAMILIAR: "Aplica subsidio familiar",
    APLICA_SUB_ESTUDIO: "Aplica subsidio de estudio",
    TIPO_CUENTA: "Tipo de cuenta bancaria",
    NUMERO_CUENTA: "Número de cuenta bancaria",
    BANCO_ASOCIADO: "Banco asociado",
    ESTADO_BEN: "Estado",
    CED_CIU: "Cédula de ciudadanía",
    CEDULA_EXTRAN: "Cédula de extranjería",
    TARJETA_IDEN: "Tarjeta de identidad",
    MASCULINO: "Masculino",
    FEMENINO: "Femenino",
    PRI_APE: "Primer apellido",
    SEG_APE: "Segundo apellido",
    PRI_NOM: "Primer nombre",
    SEG_NOM: "Segundo nombre",
    AHORROS: "Ahorros",
    CORRIENTE: "Corriente",
    ALERTA_BEN_CORRECTO: "Beneficiario registrado correctamente",
    ALERTA_BEN_INCORRECTO: "Error al registrar beneficiario",
    //FORMULARIO DE SUSTITUTOS
    TITULO_SUS: "Registro de sustituto",
    DOC_FUN_PEN: "Documento funcionario pensionado",
    DOC_BEN_SUS: "Documento beneficiario sustituto",
    PORCENTAJE: "Porcentaje asignado sobre pensión",
    ESTADO_SUS: "Estado",
    TITULO_TUTOR: "  Si el sustituto es menor de edad, se debe ingresar con el respectivo tutor",

    //FORMULARIO tutor
    TITULO_REG_TUTOR: "Registro de tutor",
    TIPO_DOC_TUTOR: "Tipo de documento",
    NUM_DOC_TUTOR: "Número de documento",
    NOM_TUTOR: "Nombres del tutor",
    APE_TUTOR: "Apellidos del tutor",
    BEN_ASOCIADO: "Beneficiario asociado",
    HABILITAR_BENEFICIARIO: "Habilitar beneficiario",
    ID_BENEFICIARIO: "IdentificaciÓn del beneficiario",
    ALERTA_SUS_INCOMPLETO: "No hay datos para ingresar información de tutor",
    ALERTA_REG_SUS_CORRECTO: "Se ha registrado correctamente el sustituto",
    ALERTA_REG_SUS_INCORRECTO: "Error al registrar sustituto",

    //Desprendible de pago
    NOMBRE_RUBRO: "Rubro",
    NOMBRE_BENEFICIARIO: "Beneficiario",
    NOMBRE_ORDEN_PAGO: "Orden de pago",
    FECHA_PDF: "Fecha",
    CONCEPTO_PDF: "Concepto",
    NOMBRE_RUBRO_ASOCIADO: "Rubro asociado",
    DETALLE_PAGO_PDF: "Detalle de pago",
    DEVENGOS_PDF: "Devengos",
    DESCUENTOS_PDF: "Descuentos",
    VALOR_PDF: "Valor",
    ALERTA_SELECCION_PERSONAS_PDF: "Seleccione personas para generar PDF",
    PAGO_PERIODO_PDF: "Pagos periodo",
    TITULO_DETALLE_PAGO_PDF: "DETALLE DE PAGO",
    TOTAL_DEVENGADO_PDF: "Total devengado",
    TOTAL_DESCUENTOS_PDF: "Total descuentos",
    //MÓDULO DE conceptos
    TITULO_GENERAL: "CONCEPTOS REGISTRADOS",
    TITULO_EDICION: "EDICIÓN DE CONCEPTO",
    TITULO_ADICION: "NUEVO CONCEPTO",
    ANADIR_CONCEPTO: "Añadir concepto",
    CONCEPTO_NOMBRE: "Nombre de concepto",
    NATURALEZA_NOMBRE: "Naturaleza",
    TIPO_NOMBRE: "Tipo",
    ACCIONES: "Acciones",
    CONFIRMACION_EDICION: "¿Está seguro de querer actualizar el concepto:",
    ACTUALIZACION_CORRECTA: "Concepto actualizado correctamente",
    ACTUALIZACION_INCORRECTA: "Error al actualizar concepto",
    CONFIRMACION_DESACTIVAR: "¿Está seguro de querer inactivar el concepto: ",
    ELIMINACION_CORRECTA: "Concepto eliminado correctamente",
    ELIMINACION_INCORRECTA: "Error al eliminar concepto",
    CONFIRMACION_ADICION: "¿Está seguro de querer agregar el concepto:",
    ADICION_CORRECTA: "Concepto agregado correctamente",
    ADICION_INCORRECTA: "Error al agregado concepto",
    ALERTA_COMPLETAR_DATOS_EDICION: "Complete todos los datos",
    ESTADO_CONCEPTO: "Estado de concepto",
    INACTIVACION_CONCEPTO_CORRECTA: "Concepto inactivado correctamente",
    INACTIVACION_CONCEPTO_INCORRECTA : "Error al inactivar concepto",
    CONFIRMACION_ACTIVAR: "¿Está seguro de querer activar el concepto: ",
    ACTIVACION_CONCEPTO_CORRECTA: "Activación realizada correctamente",
    ACTIVACION_CONCEPTO_INCORRECTA: "Error al activar concepto",
    //MENÚ GENERAL
    PENSIONADOS_MENU: "Pensionados",
    INGRESAR_BEN: "Ingresar beneficiarios",
    INGRESAR_SUS: "Ingresar sustitutos",
    NOMINA_MENU: "Nóminas",
    CONCEPTOS_MENU: "Concepto",
    NOVEDADES_MENU: "Novedades",
    REG_NOV_MENU: "Registrar novedades",
    CONS_NOV_MENU: "Consultar novedades"

};

var text_en = {
    TITULO: "GENERATOR-OAS",
    MENSAJE_INICIAL: "Now get to start to develop ...",
    VOLVER: "Back",
    SALIR: "Exit",
    REGISTRAR: "Record",
    CANCELAR: "Cancel",
    GENERAR: "Generate",
    GENERANDO: "Generating...",
    DETALLE: "Detail",
    GENERAR_PDF: "Generate PDF",
    SI: "Yes",
    NO: "No",
    ACTIVO: "Active",
    INACTIVO: "Inactive",
    CONFIRMAR: "Confirm",
    BTN:{
      EDITAR:"Edit",
      BORRAR:"Delete",
      INACTIVAR: "Inactivate",
      ACTIVAR: "Activate"
    },
    ENERO:"January",
    FEBRERO:"February",
    MARZO:"March",
    ABRIL:"April",
    MAYO:"May",
    JUNIO:"June",
    JULIO:"July",
    AGOSTO:"August",
    SEPTIEMBRE:"September",
    OCTUBRE:"October",
    NOVIEMBRE:"November",
    DICIEMBRE:"December",
    //Formulario registro y visualizaión nómina
    ANADIR_NOMINA: "Add payslip",
    TITULO_REG_NOMINA: "Payslip's record",
    NOMBRE_NOMINA: "Payslip's name",
    DESC_NOMINA: "Description",
    ESTADO_NOMINA: "Status",
    OPCIONES_NOMINA: "Options",
    PRELIQUIDACION: "Preliquidations",
    TIPO_NOMINA: "Payslip type",
    TITULO_NOMINA_REGIS: "Recorded Payslips",
    NOMINA_REG_CORRECTA: "Payslip correctly recorded",
    NOMINA_REG_INCORRECTA: "Error in payslip's record",

    //Formulario registro y visualización de preliquidacion
    ANADIR_PRELIQ: "Add pre-liquidation",
    TITULO_REG_PRELIQ: "Pre-liquidation's record",
    DESC_PRELIQ: "Description",
    ANO_PRELIQ: "Year",
    MES_PRELIQ: "Month",
    ESTADO_PRELIQ: "Status",
    TITULO_PRELIQ_REGIS: "Pre-liquidation to the payslip",
    FECHA_PRELIQ: "Record date",
    OPCIONES_PRELIQ: "Options",
    PRELIQ_REG_CORRECTA: "Pre-liquidation correctly recorded",
    PRELIQ_REG_INCORRECTA: "Error in pre-liquidation record",
    ALERTA_PRELIQUIDACION_CERRADA: "This pre-liquidation is closed",
    ALERTA_PRELIQUIDACION_OP: "This pre-liquidation is waiting for payment order",
    CAMBIO_ESTADO_OP_CORRECTO: "Payment order requested",
    CAMBIOS_ESTADO_OP_INCORRECTO: "Error in payment order request ",
    CERRADA:"Closed",
    ABIERTA:"Open",
    NEC_SOLICITADA: "Requested necesity",
    OP_SOLICITADA: "Requested payment order",
    //Interfaz de listado de personas a preliquidar
    PRELIQ_NOMINA: "People for pre-liquidation in payslip: ",
    NUM_CONTRATO: "Contract Number",
    NOMBRE_PERSONA: "Name",
    DOCUMENTO: "Identification",
    VIGENCIA: "Term",
    ALERTA_PERSONAS_SIN_SS: "The selected people cannot be pay off due to incomplete data",
    PAGOS_REALIZAR: "People to be payed this term",
    PENDIENTES_PAGO: "People with pending payment",
    NO_PRELIQ: "Pending pre-liquidation",

    //Interfaz de detalle de preliquidacion
    TITULO_DETALLE_PRELIQ: "Pre-liquidation payslip detail: ",
    RESUMEN_PRELIQ: "Pre-liquidation's summary",
    CONCEPTO: "Concept",
    VALOR: "Value",
    NATURALEZA: "Nature",
    TIPO: "Type",
    TOTAL: "Total",
    TOTAL_DEV: "Total earned:",
    TOTAL_DESC: "Total deducted:",
    TOTAL_PAGAR: "Total to pay:",
    SUELDOS_NETOS: "Net salaries:",
    GENERAR_NECESIDAD: "Create necesity",
    GENERAR_OP: "Create payment order",
    DETALLE_EMP: "Employee's detail",
    ALERTA_PERSONAS_SELECCIONADAS: "You must select people to pay off",
    ALERTA_NO_LIQUIDACION: "This Pre-liquidation has already been pay off",
    REALIZA_PAGO: "Payment?",
    TOTAL_CONT_LIQUIDADOS: "Pre-liquidated contracts",
    //REGISTRO Y CONSULTA DE NOVEDADES
    TITULO_NOVEDADES: "Changes' record",
    SELECCION_PERSONA: "Person selection",
    AGREGAR_NOVEDAD: "Add change",
    DETALLE_NOVEDAD: "Changes' detail",
    ALERTA_NO_NOVEDADES: "There are not recorded changes",
    TITULO_REG_NOVEDAD: "Adding a new change",
    NOMBRE_CONCEPTO_NOVEDAD: "Concept",
    VALOR_CONCEPTO_NOVEDAD: "Change value",
    NUMCUOTAS_CONCEPTO_NOVEDAD: "Fees",
    VALOR_CONCEPTO: "Value",
    CUOTAS_NOV: "Fees",
    TIPO_CONCEPTO: "Type",
    FECHA_INICIO: "Start date",
    FECHA_FIN: "End date",
    TITULO_EDICION_NOVEDAD: "Change edit",
    FECHA_REGISTRO: "Record date",
    NOVEDAD_REG_CORRECTO: "Change correctly recorded",
    NOVEDAD_REG_ERROR: "Error in changes' record",
    CONFIRMACION_INACTIVIDAD_NOV: "Are you sure you want to disable the change : ",
    INACTIVIDAD_CORRECTA_NOV: "Change correctly disabled",
    INACTIVIDAD_INCORRECTA_NOV: "Error in disabling change",
    CONFIRMACION_EDICION_NOV: "Are you sure you want to edit the change: ",
    EDICION_CORRECTA_NOV: "Change correctly modified",
    EDICION_INCORRECTA_NOV: "Error in modifying change",
    //FORMULARIO beneficiarios
    TITULO_REG_BEN: "Beneficiary's record",
    TIPO_DOC_BEN: "Identification type",
    NUM_DOC_BEN: "Identification",
    NOM_BEN: "Beneficiary's name",
    APE_BEN: "Beneficiary's surname",
    PARENTESCO: "Relationship",
    PARENTESCO_CON: "Relationship with",
    GENERO: "Gender",
    CORREO_ELEC: "E-mail",
    NUMERO_CONTACTO: "Contact number",
    FECHA_NAC_BEN: "Birthdate",
    APLICA_SUB_FAMILIAR: "Applies family subsidy",
    APLICA_SUB_ESTUDIO: "Applies study subsidy",
    TIPO_CUENTA: "Bank account type",
    NUMERO_CUENTA: "Bank account number",
    BANCO_ASOCIADO: "Associated bank",
    ESTADO_BEN: "Status",
    SELECCIONE: "Select...",
    CED_CIU: "Identification",
    CEDULA_EXTRAN: "Foreigner ID",
    TARJETA_IDEN: "Identity card",
    MASCULINO: "Male",
    FEMENINO: "Female",
    PRI_APE: "First surname",
    SEG_APE: "Second surname",
    PRI_NOM: "First name",
    SEG_NOM: "Second name",
    AHORROS: "Savings",
    CORRIENTE: "Checking",
    ALERTA_BEN_CORRECTO: "Beneficiary correctly recorded",
    ALERTA_BEN_INCORRECTO: "Error in record",
    //FORMULARIO DE SUSTITUTOS
    TITULO_SUS: "Substitute record",
    DOC_FUN_PEN: "Pensioned worker's ID",
    DOC_BEN_SUS: "Substitute ID",
    PORCENTAJE: "Pension's Percentage assigned to substitute",
    ESTADO_SUS: "Status",
    TITULO_TUTOR: "  If substitute is under eighteen, you must record a tutor",

    //FORMULARIO tutor
    TITULO_REG_TUTOR: "Tutor's record",
    TIPO_DOC_TUTOR: "Identification type",
    NUM_DOC_TUTOR: "Identification",
    NOM_TUTOR: "Tutor's names",
    APE_TUTOR: "Tutor's surnames",
    BEN_ASOCIADO: "Associated beneficiary",
    HABILITAR_BENEFICIARIO: "Set up beneficiary",
    ID_BENEFICIARIO: "Beneficiary ID",
    ALERTA_SUS_INCOMPLETO: "There's no data to record information about tutor",
    ALERTA_REG_SUS_CORRECTO: "Substitute correctly recorded",
    ALERTA_REG_SUS_INCORRECTO: "Error in substitute's record",

    //Desprendible pago
    NOMBRE_RUBRO: "Rubro en inglés",
    NOMBRE_BENEFICIARIO: "Beneficiary",
    NOMBRE_ORDEN_PAGO: "Payment order",
    FECHA_PDF: "Date",
    CONCEPTO_PDF: "Concept",
    NOMBRE_RUBRO_ASOCIADO: "Rubro asociado en inglés",
    DETALLE_PAGO_PDF: "Payment detail",
    DEVENGOS_PDF: "Incomes",
    DESCUENTOS_PDF: "Discounts",
    VALOR_PDF: "Values",
    ALERTA_SELECCION_PERSONAS_PDF: "Please select people to generate PDF",
    PAGO_PERIODO_PDF: "Payment for term: ",
    TITULO_DETALLE_PAGO_PDF: "Payment detail",
    TOTAL_DEVENGADO_PDF: "Total payed",
    TOTAL_DESCUENTOS_PDF: "Total deducted",

    //MODULO DE CONCEPTOS
    TITULO_GENERAL: "RECORDED CONCEPTS",
    TITULO_EDICION: "CONCEPT EDITING",
    TITULO_ADICION: "NEW CONCEPT",
    ANADIR_CONCEPTO: "Add concept",
    CONCEPTO_NOMBRE: "Concept name",
    NATURALEZA_NOMBRE: "Nature",
    TIPO_NOMBRE: "Type",
    ACCIONES: "Actions",
    CONFIRMACION_EDICION: "Are you sure you want to update the concept:",
    ACTUALIZACION_CORRECTA: "Concept correctly updated",
    ACTUALIZACION_INCORRECTA: "Error updating concept",
    CONFIRMACION_DESACTIVAR: "Are you sure you want to deactivate the concept:",
    ELIMINACION_CORRECTA: "Concept correctly deleted",
    ELIMINACION_INCORRECTA: "Error deleting concept",
    CONFIRMACION_ADICION: "Are you sure you cant to add the concept:",
    ADICION_CORRECTA: "Concept correctly added",
    ADICION_INCORRECTA: "Error adding concept",
    ALERTA_COMPLETAR_DATOS_EDICION: "Complete all data",
    ESTADO_CONCEPTO: "Concept Status",
    INACTIVACION_CONCEPTO_CORRECTA: "Concepto correctly deactivated",
    INACTIVACION_CONCEPTO_INCORRECTA : "Error deactivating concept",
    CONFIRMACION_ACTIVAR: "Are you sure you want to activate: ",
    ACTIVACION_CONCEPTO_CORRECTA: "Concept correctly activated",
    ACTIVACION_CONCEPTO_INCORRECTA: "Error activating concept",

    //MENÚ GENERAL
    PENSIONADOS_MENU: "Retirees",
    INGRESAR_BEN: "Record beneficiaries",
    INGRESAR_SUS: "Record substitutes",
    NOMINA_MENU: "Payslips",
    CONCEPTOS_MENU: "Concepts",
    NOVEDADES_MENU: "Changes",
    REG_NOV_MENU: "Record changes",
    CONS_NOV_MENU: "List changes"

};

angular.module('titanClienteV2App')
    .config(function($translateProvider) {
        $translateProvider
            .translations("es", text_es)
            .translations("en", text_en);
        $translateProvider.preferredLanguage("es");
        $translateProvider.useSanitizeValueStrategy("sanitizeParameters");
    });
